/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as ProjectsProjectIdMembersRouteImport } from './routes/projects.$projectId.members'
import { Route as ProjectsProjectIdRunsRouteImport } from './routes/projects.$projectId.runs'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects.$projectId.settings'
import { Route as ProjectsProjectIdTestsRouteImport } from './routes/projects.$projectId.tests'
import { Route as ProjectsProjectIdTestsTestIdRouteImport } from './routes/projects.$projectId.tests.$testId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdMembersRoute =
  ProjectsProjectIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdRunsRoute = ProjectsProjectIdRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdTestsRoute = ProjectsProjectIdTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdTestsTestIdRoute =
  ProjectsProjectIdTestsTestIdRouteImport.update({
    id: '/$testId',
    path: '/$testId',
    getParentRoute: () => ProjectsProjectIdTestsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/members': typeof ProjectsProjectIdMembersRoute
  '/projects/$projectId/runs': typeof ProjectsProjectIdRunsRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/tests': typeof ProjectsProjectIdTestsRouteWithChildren
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/tests/$testId': typeof ProjectsProjectIdTestsTestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/projects/$projectId/members': typeof ProjectsProjectIdMembersRoute
  '/projects/$projectId/runs': typeof ProjectsProjectIdRunsRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/tests': typeof ProjectsProjectIdTestsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/tests/$testId': typeof ProjectsProjectIdTestsTestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/members': typeof ProjectsProjectIdMembersRoute
  '/projects/$projectId/runs': typeof ProjectsProjectIdRunsRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/tests': typeof ProjectsProjectIdTestsRouteWithChildren
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/tests/$testId': typeof ProjectsProjectIdTestsTestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/login'
    | '/projects/$projectId'
    | '/projects/$projectId/members'
    | '/projects/$projectId/runs'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/tests'
    | '/projects/$projectId/'
    | '/projects/$projectId/tests/$testId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/login'
    | '/projects/$projectId/members'
    | '/projects/$projectId/runs'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/tests'
    | '/projects/$projectId'
    | '/projects/$projectId/tests/$testId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/login'
    | '/projects/$projectId'
    | '/projects/$projectId/members'
    | '/projects/$projectId/runs'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/tests'
    | '/projects/$projectId/'
    | '/projects/$projectId/tests/$testId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  LoginRoute: typeof LoginRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/members': {
      id: '/projects/$projectId/members'
      path: '/members'
      fullPath: '/projects/$projectId/members'
      preLoaderRoute: typeof ProjectsProjectIdMembersRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/runs': {
      id: '/projects/$projectId/runs'
      path: '/runs'
      fullPath: '/projects/$projectId/runs'
      preLoaderRoute: typeof ProjectsProjectIdRunsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/tests': {
      id: '/projects/$projectId/tests'
      path: '/tests'
      fullPath: '/projects/$projectId/tests'
      preLoaderRoute: typeof ProjectsProjectIdTestsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/tests/$testId': {
      id: '/projects/$projectId/tests/$testId'
      path: '/$testId'
      fullPath: '/projects/$projectId/tests/$testId'
      preLoaderRoute: typeof ProjectsProjectIdTestsTestIdRouteImport
      parentRoute: typeof ProjectsProjectIdTestsRoute
    }
  }
}

interface ProjectsProjectIdTestsRouteChildren {
  ProjectsProjectIdTestsTestIdRoute: typeof ProjectsProjectIdTestsTestIdRoute
}

const ProjectsProjectIdTestsRouteChildren: ProjectsProjectIdTestsRouteChildren =
  {
    ProjectsProjectIdTestsTestIdRoute: ProjectsProjectIdTestsTestIdRoute,
  }

const ProjectsProjectIdTestsRouteWithChildren =
  ProjectsProjectIdTestsRoute._addFileChildren(
    ProjectsProjectIdTestsRouteChildren,
  )

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdMembersRoute: typeof ProjectsProjectIdMembersRoute
  ProjectsProjectIdRunsRoute: typeof ProjectsProjectIdRunsRoute
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRoute
  ProjectsProjectIdTestsRoute: typeof ProjectsProjectIdTestsRouteWithChildren
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdMembersRoute: ProjectsProjectIdMembersRoute,
  ProjectsProjectIdRunsRoute: ProjectsProjectIdRunsRoute,
  ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRoute,
  ProjectsProjectIdTestsRoute: ProjectsProjectIdTestsRouteWithChildren,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  LoginRoute: LoginRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
