server {
    listen 80;
    listen [::]:80;
    server_name __NAMES__;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    location / {
        __HTTP_RESPONSE__
    }
}
