#!/usr/bin/env bash
# Internal remote helper. Invoke provision-app.sh from your workstation.
set -euo pipefail
umask 077
export PATH=/usr/sbin:/usr/bin:/sbin:/bin
export DEBIAN_FRONTEND=noninteractive
die() { printf 'Error: %s\n' "$*" >&2; exit 1; }
[ "$EUID" -eq 0 ] || die 'Root privileges required'
STAGE=${1:?Internal staging directory required}
PHASE=${2:?Internal phase required}
# Generated by provision-app.sh using printf %q, not a user-provided env file.
# shellcheck source=/dev/null
. "$STAGE/settings.sh"
exec 9>/run/lock/testron-provision.lock
flock -n 9 || die 'Another provision run is active'
# shellcheck source=/dev/null
. /etc/os-release
case "$ID:$VERSION_ID" in
  debian:13) ;;
  *) die "Unsupported OS: $ID $VERSION_ID (requires Debian 13 with systemd)" ;;
esac

install_packages() {
  local pkg missing=()
  for pkg in nginx certbot sudo curl ca-certificates openssh-server; do
    [ "$(dpkg-query -W -f='${Status}' "$pkg" 2>/dev/null || true)" = 'install ok installed' ] || missing+=("$pkg")
  done
  if [ "${#missing[@]}" -gt 0 ]; then apt-get update; apt-get install -y "${missing[@]}"; fi
  missing=()
  for pkg in docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin; do
    [ "$(dpkg-query -W -f='${Status}' "$pkg" 2>/dev/null || true)" = 'install ok installed' ] || missing+=("$pkg")
  done
  if [ "${#missing[@]}" -gt 0 ]; then
    # Avoid silently uninstalling an existing distribution Docker/containerd.
    for pkg in docker.io docker-compose docker-compose-v2 docker-doc docker-buildx podman-docker containerd runc; do
      [ "$(dpkg-query -W -f='${Status}' "$pkg" 2>/dev/null || true)" != 'install ok installed' ] \
        || die "Conflicting package $pkg installed; migrate it to Docker CE before provisioning"
    done
    install -d -m 0755 /etc/apt/keyrings
    curl -fsSL "https://download.docker.com/linux/$ID/gpg" -o "$STAGE/docker.asc"
    install -m 0644 "$STAGE/docker.asc" /etc/apt/keyrings/docker.asc
    cat > /etc/apt/sources.list.d/docker.sources <<EOF
Types: deb
URIs: https://download.docker.com/linux/$ID
Suites: ${UBUNTU_CODENAME:-$VERSION_CODENAME}
Components: stable
Architectures: $(dpkg --print-architecture)
Signed-By: /etc/apt/keyrings/docker.asc
EOF
    apt-get update
    apt-get install -y "${missing[@]}"
  fi
  systemctl enable --now docker nginx certbot.timer
  docker compose version
}

install_keys() {
  local user=$1 keys=$2 user_home key
  if ! id "$user" >/dev/null 2>&1; then useradd --create-home --shell /bin/bash "$user"; fi
  user_home=$(getent passwd "$user" | cut -d: -f6)
  [ -d "$user_home" ] || die "Missing home for $user"
  install -d -m 0700 -o "$user" -g "$(id -gn "$user")" "$user_home/.ssh"
  touch "$user_home/.ssh/authorized_keys"
  while IFS= read -r key || [ -n "$key" ]; do
    if ! grep -qxF -- "$key" "$user_home/.ssh/authorized_keys"; then
      # Leading newline also handles an existing file with no final newline.
      printf '\n%s\n' "$key" >> "$user_home/.ssh/authorized_keys"
    fi
  done < "$keys"
  chown "$user:$(id -gn "$user")" "$user_home/.ssh/authorized_keys"
  chmod 0600 "$user_home/.ssh/authorized_keys"
}

prepare_users() {
  install_keys github "$STAGE/DEPLOY_KEY_FILE"
  install_keys "$DEVELOPER_USER" "$STAGE/DEVELOPER_KEYS_FILE"
  usermod -aG docker github
  printf '%s ALL=(ALL:ALL) NOPASSWD: ALL\n' "$DEVELOPER_USER" > "$STAGE/sudoers"
  chmod 0440 "$STAGE/sudoers"
  visudo -cf "$STAGE/sudoers"
  install -m 0440 "$STAGE/sudoers" /etc/sudoers.d/90-testron-developer
  install -d -m 0755 -o github -g "$(id -gn github)" /opt/testron /var/www/testron.dev /var/www/testron.dev/releases
  # Do not recursively chown restored data. Postgres manages its own directory.
  mkdir -p /data/testron/db /data/testron/artifacts
  # node in Dockerfile.server is uid/gid 1000. Bind mounts override image ownership.
  chown 1000:1000 /data/testron/artifacts
  chmod 0755 /data/testron/artifacts
}

nginx_pending=0; nginx_backup=''; ssh_pending=0; ssh_backup=''
reload_ssh() { systemctl reload ssh; }
rollback() {
  local rc=$?
  trap - EXIT
  if [ "$nginx_pending" = 1 ]; then
    printf 'Restoring nginx from %s\n' "$nginx_backup" >&2
    if rm -rf /etc/nginx \
      && cp -a "$nginx_backup/nginx" /etc/nginx \
      && nginx -t && systemctl reload nginx \
      && rm -rf "$nginx_backup"; then
      nginx_pending=0
    else
      printf 'nginx rollback or cleanup failed; backup retained at %s\n' "$nginx_backup" >&2
    fi
  fi
  if [ "$ssh_pending" = 1 ]; then
    printf 'Restoring sshd from %s\n' "$ssh_backup" >&2
    if cp -a "$ssh_backup/sshd_config" /etc/ssh/sshd_config \
      && rm -f /etc/ssh/testron-hardening.conf \
      && { [ ! -f "$ssh_backup/testron-hardening.conf" ] || cp -a "$ssh_backup/testron-hardening.conf" /etc/ssh/; } \
      && sshd -t && reload_ssh \
      && rm -rf "$ssh_backup"; then
      ssh_pending=0
    else
      printf 'sshd rollback or cleanup failed; backup retained at %s\n' "$ssh_backup" >&2
    fi
  fi
  exit "$rc"
}
trap rollback EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

has_cert() {
  [ -s "/etc/letsencrypt/live/$1/fullchain.pem" ] && [ -s "/etc/letsencrypt/live/$1/privkey.pem" ]
}

render_sites() {
  local domain names response
  for domain in app.testron.dev testron.dev; do
    names=$domain
    if [ "$domain" = testron.dev ] && [ "$INCLUDE_WWW" = 1 ]; then names="$names www.testron.dev"; fi
    response='return 503;'
    # shellcheck disable=SC2016 # These variables belong to nginx.
    if has_cert "$domain"; then response='return 301 https://$host$request_uri;'; fi
    sed -e "s/__NAMES__/$names/g" -e "s|__HTTP_RESPONSE__|$response|g" \
      "$STAGE/nginx/http.conf" > "/etc/nginx/sites-available/$domain.conf"
    if has_cert "$domain"; then
      sed "s/__WEB_NAMES__/$names/g" "$STAGE/nginx/$domain.conf" >> "/etc/nginx/sites-available/$domain.conf"
    fi
    chmod 0644 "/etc/nginx/sites-available/$domain.conf"
    # Also replaces the corresponding old Ansible site, without touching other sites.
    rm -f "/etc/nginx/sites-enabled/$domain"
    ln -sfn "/etc/nginx/sites-available/$domain.conf" "/etc/nginx/sites-enabled/$domain.conf"
  done
  nginx -t
  systemctl reload nginx
}

configure_nginx() {
  command -v nginx >/dev/null || die 'Run full provisioning to install nginx first'
  if [ "$MODE" = nginx ]; then
    for domain in app.testron.dev testron.dev; do
      has_cert "$domain" || die "Missing $domain certificate; run full provisioning or --certs-only"
    done
  fi
  if { [ "$MODE" = nginx ] || [ "$SKIP_CERTS" = 1 ]; } && [ "$INCLUDE_WWW" = 1 ] && has_cert testron.dev; then
    openssl x509 -in /etc/letsencrypt/live/testron.dev/fullchain.pem -noout -checkhost www.testron.dev \
      | grep -q 'does match certificate' || die 'Issue a certificate covering www with --certs-only first'
  fi
  if [ "$MODE" != nginx ] && [ "$SKIP_CERTS" = 0 ]; then
    command -v certbot >/dev/null || die 'Run full provisioning to install certbot first'
  fi
  # Keep the previous working configuration until all issuance and reloads succeed.
  nginx -t
  nginx_backup=$(mktemp -d /var/backups/testron-nginx.XXXXXXXX)
  cp -a /etc/nginx "$nginx_backup/nginx"
  nginx_pending=1
  install -d -m 0755 /var/www/certbot /etc/nginx/snippets
  if [ -n "$SLANG_API_KEY" ]; then
    cat > /etc/nginx/snippets/testron-slang.conf <<EOF
# Only included in the two exact read-only locations.
rewrite ^/slang/(.*)\$ /\$1 break;
proxy_pass https://slang.warpunit.com;
proxy_ssl_server_name on;
proxy_set_header Host slang.warpunit.com;
proxy_set_header X-Api-Key "$SLANG_API_KEY";
proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto \$scheme;
EOF
  else
    printf 'return 503;\n' > /etc/nginx/snippets/testron-slang.conf
  fi
  chmod 0600 /etc/nginx/snippets/testron-slang.conf
  render_sites
  if [ "$MODE" != nginx ] && [ "$SKIP_CERTS" = 0 ]; then
    install -d -m 0755 /etc/letsencrypt/renewal-hooks/deploy
    cat > /etc/letsencrypt/renewal-hooks/deploy/testron-nginx <<'EOF'
#!/bin/sh
set -eu
nginx -t
systemctl reload nginx
EOF
    chmod 0755 /etc/letsencrypt/renewal-hooks/deploy/testron-nginx
    for domain in app.testron.dev testron.dev; do
      names=(-d "$domain")
      if [ "$domain" = testron.dev ] && [ "$INCLUDE_WWW" = 1 ]; then names+=(-d www.testron.dev); fi
      certbot certonly --webroot -w /var/www/certbot --cert-name "$domain" \
        "${names[@]}" --email "$CERT_EMAIL" --agree-tos --non-interactive \
        --keep-until-expiring --expand
    done
    render_sites
    systemctl enable --now certbot.timer
  fi
  nginx_pending=0
  rm -rf "$nginx_backup"
}

harden_ssh() {
  sshd -t
  ssh_backup=$(mktemp -d /var/backups/testron-ssh.XXXXXXXX)
  cp -a /etc/ssh/sshd_config "$ssh_backup/"
  [ ! -f /etc/ssh/testron-hardening.conf ] || cp -a /etc/ssh/testron-hardening.conf "$ssh_backup/"
  ssh_pending=1
  cat > /etc/ssh/testron-hardening.conf <<EOF
PasswordAuthentication no
KbdInteractiveAuthentication no
PermitEmptyPasswords no
PubkeyAuthentication yes
PermitRootLogin $PERMIT_ROOT_LOGIN
EOF
  chmod 0644 /etc/ssh/testron-hardening.conf
  # sshd uses the first value: prepend an explicit include ahead of cloud-init.
  # Preserve all provider settings and Match blocks, then check effective values.
  {
    printf 'Include /etc/ssh/testron-hardening.conf\n'
    sed '\|^Include /etc/ssh/testron-hardening.conf$|d' "$ssh_backup/sshd_config"
  } > /etc/ssh/sshd_config
  sshd -t
  local user effective client_addr=${SSH_CONNECTION:-127.0.0.1}
  client_addr=${client_addr%% *}
  for user in root github "$DEVELOPER_USER"; do
    effective=$(sshd -T -C "user=$user,host=localhost,addr=$client_addr")
    for setting in 'passwordauthentication no' 'kbdinteractiveauthentication no' 'pubkeyauthentication yes'; do
      grep -qxF "$setting" <<< "$effective" || die "Conflicting SSH Match rule for $user: expected $setting"
    done
    if grep '^authenticationmethods ' <<< "$effective" | grep -Eq 'password|keyboard-interactive'; then
      die "SSH AuthenticationMethods for $user still requires a password"
    fi
    if [ "$user" = root ]; then
      expected_root=$PERMIT_ROOT_LOGIN
      [ "$expected_root" != prohibit-password ] || expected_root=without-password
      grep -qxF "permitrootlogin $expected_root" <<< "$effective" || die 'Conflicting root login policy'
    fi
  done
  reload_ssh
  ssh_pending=0
  rm -rf "$ssh_backup"
  printf 'SSH now requires keys. Keep your session open and verify a new developer login.\n'
}

case "$PHASE" in
  prepare)
    if [ "$MODE" = full ]; then install_packages; prepare_users; fi
    configure_nginx ;;
  harden) harden_ssh ;;
  *) die "Unknown phase: $PHASE" ;;
esac
