import type { TestRevisionContent } from '@testron/protocol';
import { testExecutionMode } from '@testron/protocol';
import { generatePlaywright } from '@testron/domain/codegen/playwright';
import { parsePlaywright, playwrightReplayError } from '@testron/domain/codegen/parse-playwright';
import { annotateExport } from './discovery';
import { CliError } from './files';

// Deliberately contains no server URL, profile values, cookies, or remote storage state.
export const importedFixture = `// Generated by testron pull. Local/CI settings only.
import { test as base, expect } from '@playwright/test';

export const test = base.extend({
  baseURL: async ({}, use) => {
    const target = process.env.TESTRON_BASE_URL;
    if (!target) throw new Error('Set TESTRON_BASE_URL to your local or CI application URL. No Testron environment is used automatically.');
    const url = new URL(target);
    if (!['http:', 'https:'].includes(url.protocol) || url.username || url.password)
      throw new Error('TESTRON_BASE_URL must be an HTTP(S) URL without credentials.');
    await use(url.origin);
  },
  storageState: async ({}, use, testInfo) => {
    const state = process.env.TESTRON_STORAGE_STATE;
    const needsAuth = testInfo.annotations.some(item => item.type === 'testron.local-auth');
    if (needsAuth && !state)
      throw new Error('This imported test needs authentication. Set TESTRON_STORAGE_STATE to a storage-state file created by your local/CI login setup. Testron credentials are not exported.');
    await use(needsAuth ? state! : { cookies: [], origins: [] });
  },
});
export { expect };
test.beforeEach(async ({ baseURL }, testInfo) => {
  const target = process.env.TESTRON_BASE_URL;
  if (!target) throw new Error('Set TESTRON_BASE_URL to your local or CI application URL.');
  if (baseURL !== new URL(target).origin)
    throw new Error('The Playwright baseURL overrides TESTRON_BASE_URL. Configure this imported test project to use the explicit local/CI target.');
  if (testInfo.annotations.some(item => item.type === 'testron.local-auth') && !process.env.TESTRON_STORAGE_STATE)
    throw new Error('Set TESTRON_STORAGE_STATE from your local/CI login setup.');
});
`;

export function exportTestSource(content: TestRevisionContent, id: string, suite: string | null) {
  const source =
    content.source ??
    generatePlaywright(
      content.title,
      content.steps.map(({ payload }) => payload),
    );
  // Never silently discard custom code, hooks, or requests while adapting the target.
  if (playwrightReplayError(source))
    throw new CliError(
      'SOURCE_EXPORT_UNSUPPORTED',
      `Test ${id} contains custom code. Adapt it in the repository before synchronizing; automatic local-target export supports structured Playwright tests.`,
    );
  const parsed = parsePlaywright(source);
  const origins = new Set<string>();
  const steps = parsed.steps.map(({ step }) => {
    if (step.kind !== 'navigate') return step;
    let url: URL;
    try {
      url = new URL(step.url);
    } catch {
      if (step.url.startsWith('/') && !step.url.startsWith('//')) return step;
      throw new CliError(
        'SOURCE_EXPORT_UNSUPPORTED',
        `Test ${id} has an unsupported navigation target.`,
      );
    }
    if (!['http:', 'https:'].includes(url.protocol) || url.username || url.password)
      throw new CliError(
        'SOURCE_EXPORT_UNSUPPORTED',
        `Test ${id} has an unsupported navigation target.`,
      );
    origins.add(url.origin);
    if (url.pathname.startsWith('//'))
      throw new CliError(
        'SOURCE_EXPORT_UNSUPPORTED',
        `Test ${id} has a protocol-relative navigation path. Adapt it explicitly.`,
      );
    return { ...step, url: `${url.pathname}${url.search}${url.hash}` };
  });
  if (origins.size > 1)
    throw new CliError(
      'SOURCE_EXPORT_UNSUPPORTED',
      `Test ${id} navigates multiple origins. Configure local equivalents explicitly before importing.`,
    );
  return annotateExport(
    generatePlaywright(parsed.title, steps).replace(
      "from '@playwright/test'",
      "from './testron.fixture'",
    ),
    id,
    suite,
    testExecutionMode(content),
    Boolean(content.profileId),
    content,
  );
}
