import path from 'node:path';
import { lstat, mkdir } from 'node:fs/promises';
import { createTRPCClient, httpLink } from '@trpc/client';
import type { inferRouterOutputs } from '@trpc/server';
import type { AppRouter } from '@testron/server/router';
import {
  syncPushSchema,
  testExecutionMode,
  isCatalogueTest,
  type SyncPush,
} from '@testron/protocol';
import type { Config } from './config';
import { atomicWrite, CliError, hash, jsonWrite, readOptional, sourcePath } from './files';
import { publicationSource } from './publication';
import { exportTestSource, importedFixture } from './export-test';
import {
  assignIds,
  discover,
  logicalTests,
  publication,
  suiteId,
  testId,
  validateTests,
} from './discovery';

export type Catalog = inferRouterOutputs<AppRouter>['sync']['pull'];
export type Api = ReturnType<typeof apiClient>;
export const apiClient = (server: string, token?: string) =>
  createTRPCClient<AppRouter>({
    links: [
      httpLink({
        url: `${server.replace(/\/$/, '')}/api/trpc`,
        headers: token ? { authorization: `Bearer ${token}` } : {},
        fetch: (url, options) =>
          fetch(url, { ...options, redirect: 'error', signal: AbortSignal.timeout(60_000) }),
      }),
    ],
  });
interface State {
  binding: string;
  files: Record<string, string>;
  remoteFiles?: Record<string, string | null>;
  tests: Record<string, { id: string; number: number }>;
}
const binding = (config: Config) =>
  JSON.stringify([config.server, config.projectId, config.repositoryId]);
async function localDirectory(root: string) {
  const dir = path.join(root, '.testron');
  await mkdir(dir, { recursive: true });
  if ((await lstat(dir)).isSymbolicLink())
    throw new CliError('UNSAFE_PATH', '.testron cannot be a symlink.');
  return dir;
}
async function loadState(root: string, config: Config): Promise<State> {
  const dir = await localDirectory(root);
  const raw = await readOptional(path.join(dir, 'state.json'));
  const state: State = raw ? JSON.parse(raw) : { binding: binding(config), files: {}, tests: {} };
  if (state.binding !== binding(config))
    throw new CliError(
      'PROJECT_CHANGED',
      'Local sync state belongs to a different server, project, or repository. Use a separate checkout.',
    );
  return state;
}
export function generateReferences(catalog: Pick<Catalog, 'suites'>) {
  const values = Object.fromEntries(
    catalog.suites.map((suite) => [
      suite.codeKey ?? `Suite_${suite.id.replaceAll('-', '')}`,
      suite.id,
    ]),
  );
  return `// Generated by testron pull. Commit this file; do not edit it.\nexport const suites = ${JSON.stringify(values, null, 2)} as const;\nexport type SuiteId = (typeof suites)[keyof typeof suites];\n\nexport function testron(options: { id?: string; suite?: SuiteId; publish?: boolean; execution?: 'ci-only' | 'ci-and-testron'; description?: string; steps?: string[] }): { annotation: { type: string; description: string }[] } {\n  return { annotation: [\n    ...(options.id ? [{ type: 'testron.id', description: options.id }] : []),\n    ...(options.suite ? [{ type: 'testron.suite', description: options.suite }] : []),\n    ...(options.publish !== undefined ? [{ type: 'testron.publish', description: String(options.publish) }] : []),\n    ...(options.execution ? [{ type: 'testron.execution', description: options.execution }] : []),\n    ...(options.description !== undefined ? [{ type: 'testron.description', description: options.description }] : []),\n    ...(options.steps ? [{ type: 'testron.steps', description: JSON.stringify(options.steps) }] : []),\n  ] };\n}\n`;
}
async function cacheCatalog(root: string, catalog: Catalog) {
  const dir = await localDirectory(root);
  await jsonWrite(path.join(dir, 'catalog.json'), {
    suites: catalog.suites,
    environments: catalog.environments,
    tests: catalog.tests.map(({ test, currentRevision }) => ({
      id: test.id,
      title: test.title,
      suiteId: test.testSuiteId,
      revision: test.currentRevision,
      status: currentRevision.content.status ?? 'ready',
      description: currentRevision.content.description,
      repository: currentRevision.content.repository,
      origin:
        currentRevision.content.repository?.origin ??
        (currentRevision.content.repository ? 'repository' : 'testron'),
      execution: testExecutionMode(currentRevision.content),
    })),
  });
  await atomicWrite(
    await sourcePath(root, 'testron.generated.ts', true),
    generateReferences(catalog),
  );
}

export async function pull(
  root: string,
  config: Config,
  api: Api,
  options: { tests?: boolean; test?: string; suite?: string },
) {
  const state = await loadState(root, config);
  const catalog = await api.sync.pull.query({
    projectId: config.projectId,
    repositoryId: config.repositoryId,
  });
  let selected = catalog.tests;
  if (options.test) {
    selected = selected.filter(({ test }) => test.id === options.test);
    if (!selected.length)
      throw new CliError('TEST_NOT_FOUND', `No test ${options.test} in this project.`);
  }
  if (options.suite) {
    const suite = catalog.suites.find(
      (suite) => suite.id === options.suite || suite.codeKey === options.suite,
    );
    if (!suite) throw new CliError('SUITE_UNKNOWN', `Unknown suite ${options.suite}.`);
    selected = selected.filter(({ test }) => test.testSuiteId === suite.id);
  }
  const writes: { file: string; source: string; relative: string; hash: string }[] = [];
  const kept: string[] = [];
  if (options.tests || options.test) {
    const wanted = new Set(
      selected.flatMap(({ currentRevision }) => {
        const repository = currentRevision.content.repository;
        return isCatalogueTest(currentRevision.content) && repository?.id === config.repositoryId
          ? (repository.files ?? [repository.file])
          : [];
      }),
    );
    const conflicts: string[] = [];
    for (const file of catalog.files.filter((file) => wanted.has(file.path))) {
      if (file.path === 'testron.generated.ts') continue;
      const absolute = await sourcePath(root, file.path, true);
      const local = await readOptional(absolute);
      const localHash = local === undefined ? null : hash(local);
      const base = state.files[file.path] ?? null;
      if (localHash === file.hash) {
        state.files[file.path] = file.hash;
        continue;
      }
      if (base === file.hash) {
        kept.push(file.path);
        continue;
      }
      if (localHash !== base) {
        conflicts.push(file.path);
        continue;
      }
      writes.push({ file: absolute, source: file.source, relative: file.path, hash: file.hash });
    }
    const native = selected.filter(
      ({ currentRevision }) =>
        !isCatalogueTest(currentRevision.content) && currentRevision.content.status !== 'requested',
    );
    const importDir = config.importDir ?? 'tests/testron';
    if (native.length) {
      const relative = `${importDir}/testron.fixture.ts`;
      const absolute = await sourcePath(root, relative, true);
      const local = await readOptional(absolute);
      const localHash = local === undefined ? null : hash(local);
      const remoteHash = hash(importedFixture);
      const base = state.files[relative] ?? null;
      if (localHash === remoteHash) state.files[relative] = remoteHash;
      else if (base === remoteHash) kept.push(relative);
      else if (localHash !== base) conflicts.push(relative);
      else writes.push({ file: absolute, source: importedFixture, relative, hash: remoteHash });
    }
    for (const snapshot of native) {
      const content = snapshot.currentRevision.content;
      const source = exportTestSource(content, snapshot.test.id, snapshot.test.testSuiteId);
      const relative =
        content.repository?.id === config.repositoryId
          ? content.repository.file
          : `${importDir}/${snapshot.test.id}.spec.ts`;
      const fixtureRelative = path.posix.relative(
        path.posix.dirname(relative),
        `${importDir}/testron.fixture`,
      );
      const localSource = source.replace(
        "from './testron.fixture'",
        `from '${fixtureRelative.startsWith('.') ? fixtureRelative : './' + fixtureRelative}'`,
      );
      const absolute = await sourcePath(root, relative, true);
      const local = await readOptional(absolute);
      const localHash = local === undefined ? null : hash(local);
      const remoteHash = hash(localSource);
      const base = state.files[relative] ?? null;
      const remoteFile = catalog.files.find((file) => file.path === relative);
      (state.remoteFiles ??= {})[relative] = remoteFile?.hash ?? null;
      if (localHash === remoteHash) {
        state.files[relative] = remoteHash;
        state.tests[snapshot.test.id] = snapshot.test.currentRevision;
        continue;
      }
      if (base === remoteHash) {
        kept.push(relative);
        continue;
      }
      if (localHash !== base) {
        conflicts.push(relative);
        continue;
      }
      writes.push({ file: absolute, source: localSource, relative, hash: remoteHash });
      state.tests[snapshot.test.id] = snapshot.test.currentRevision;
    }
    if (conflicts.length)
      throw new CliError(
        'PULL_CONFLICT',
        'Local and remote sources differ. Reconcile these files before pulling; nothing was overwritten.',
        { files: conflicts },
      );
    for (const write of writes) {
      await atomicWrite(write.file, write.source);
      state.files[write.relative] = write.hash;
    }
    for (const snapshot of catalog.tests) {
      const repository = snapshot.currentRevision.content.repository;
      if (
        repository?.id === config.repositoryId &&
        wanted.has(repository.file) &&
        !kept.includes(repository.file)
      )
        state.tests[snapshot.test.id] = snapshot.test.currentRevision;
    }
    const generated = catalog.files.find((file) => file.path === 'testron.generated.ts');
    if (generated && wanted.has(generated.path)) state.files[generated.path] = generated.hash;
    const requests = selected.filter(
      ({ currentRevision }) => currentRevision.content.status === 'requested',
    );
    await jsonWrite(
      path.join(root, '.testron', 'requests.json'),
      requests.map(({ test, currentRevision }) => ({
        id: test.id,
        title: test.title,
        description: currentRevision.content.description,
        suiteId: test.testSuiteId,
      })),
    );
  }
  // Refresh metadata without advancing source baselines for ordinary catalog pulls.
  await cacheCatalog(root, catalog);
  await jsonWrite(path.join(root, '.testron', 'state.json'), state);
  return {
    suites: catalog.suites.map(({ id, name, codeKey }) => ({ id, name, codeKey })),
    tests: selected.map(({ test, currentRevision }) => ({
      id: test.id,
      title: test.title,
      suiteId: test.testSuiteId,
      status: currentRevision.content.status ?? 'ready',
      execution: testExecutionMode(currentRevision.content),
      origin:
        currentRevision.content.repository?.origin ??
        (currentRevision.content.repository ? 'repository' : 'testron'),
    })),
    files: writes.map(({ relative }) => relative),
    keptLocal: kept,
    environments: catalog.environments,
  };
}

export async function push(
  root: string,
  config: Config,
  api: Api,
  options: { file?: string; dryRun?: boolean },
) {
  const state = await loadState(root, config);
  const catalog = await api.sync.pull.query({
    projectId: config.projectId,
    repositoryId: config.repositoryId,
  });
  let all = logicalTests(await discover(root, config));
  // IDs must remain unique across the entire collected repository, including partial pushes.
  const ids = new Set<string>();
  for (const test of all) {
    const id = testId(test);
    if (id && ids.has(id))
      throw new CliError('DUPLICATE_ID', `Test ID ${id} is reused at ${test.file}:${test.line}.`);
    if (id) ids.add(id);
  }
  const file = options.file
    ? path.relative(root, path.resolve(root, options.file)).split(path.sep).join('/')
    : undefined;
  const matching = () => all.filter((test) => !file || test.file === file);
  const select = () => matching().filter(publication);
  let selected = select();
  if (!selected.length)
    throw new CliError(
      matching().length ? 'NO_PUBLISHED_TESTS' : 'NO_TESTS',
      matching().length
        ? 'No tests opted into publication. Add testron({ publish: true }) to a test or describe; -f does not override this.'
        : 'No tests matched the selected file or Playwright configuration.',
    );
  validateTests(
    selected,
    new Set(catalog.suites.map((suite) => suite.id)),
    new Set(catalog.tests.filter((item) => !item.test.testSuiteId).map((item) => item.test.id)),
  );
  const assigned = await assignIds(root, selected, Boolean(options.dryRun));
  if (assigned.size && !options.dryRun) {
    all = logicalTests(await discover(root, config));
    selected = select();
    validateTests(
      selected,
      new Set(catalog.suites.map((suite) => suite.id)),
      new Set(catalog.tests.filter((item) => !item.test.testSuiteId).map((item) => item.test.id)),
    );
  }
  const publications = await Promise.all(selected.map((test) => publicationSource(root, test)));
  const files = new Map<string, string>();
  for (const test of selected)
    if (!files.has(test.file))
      files.set(test.file, (await readOptional(await sourcePath(root, test.file)))!);
  const request: SyncPush = syncPushSchema.parse({
    projectId: config.projectId,
    repositoryId: config.repositoryId,
    dryRun: Boolean(options.dryRun),
    environmentIds: config.environmentIds,
    files: [...files].map(([path, source]) => ({
      path,
      source,
      baseHash:
        state.remoteFiles && path in state.remoteFiles
          ? state.remoteFiles[path]
          : (state.files[path] ?? null),
    })),
    tests: selected.map((test, index) => {
      const id = testId(test) ?? assigned.get(`${test.file}:${test.line}:${test.column}`)!;
      const remote = catalog.tests.find((snapshot) => snapshot.test.id === id);
      // Linking a recorder/request test is explicit through its annotation. Repository updates require a local baseline.
      const baseRevision =
        state.tests[id] ??
        (remote && !remote.currentRevision.content.repository ? remote.test.currentRevision : null);
      return {
        id,
        suiteId: suiteId(test) ?? remote?.test.testSuiteId ?? null,
        kind: publications[index]!.kind,
        execution: publications[index]!.execution,
        source: publications[index]!.source,
        description: publications[index]!.description,
        humanSteps: publications[index]!.humanSteps,

        title: test.title,
        file: test.file,
        titlePath: test.titlePath,
        line: test.line,
        baseRevision,
      };
    }),
  });
  const result = await api.sync.push.mutate(request);
  if (!options.dryRun) {
    for (const file of result.files) {
      state.files[file.path] = file.hash;
      (state.remoteFiles ??= {})[file.path] = file.hash;
    }
    for (const test of result.tests) if (test.revision) state.tests[test.id] = test.revision;
    await jsonWrite(path.join(root, '.testron', 'state.json'), state);
  }
  return {
    ...result,
    idsAssigned: assigned.size,
    downgraded: selected
      .filter(
        (_test, index) =>
          publications[index]?.downgrade ||
          (request.tests[index]?.execution === 'ci-and-testron' &&
            result.tests.some(
              (test) => test.id === request.tests[index]?.id && test.execution === 'ci-only',
            )),
      )
      .map((test) => test.title),
    tests: result.tests.map((test) => ({
      ...test,
      url: `${config.server.replace(/\/$/, '')}/projects/${config.projectId}/tests/${test.id}`,
    })),
  };
}
